micronaut:
  application:
    name: threshr-cli
  http:
    services:
      redsky-api:
        url: https://redsky.target.com/
        path: redsky_aggregations/v1/web
test:
  datasources:
    default:
      url:
