name: Run Maven Tests
on:
  push:
jobs:
  test:
    env:
      THRESHR_KEY: ${{ vars.THRESHR_KEY }}
      THRESHR_CHANNEL: ${{ vars.THRESHR_CHANNEL }}
      USERNAME: jonathan-zollinger
      PASSWORD: ${{ secrets.READ_PACKAGES }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Test with Maven
        run: mvn -U -B test --file pom.xml --settings settings.xml