name: Run Sonar Scan

on:
  push:
    branches:
    - main
    - release/*
  pull_request:

jobs:
  test:
    environment: redsky api
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/virtual-environments/issues/709
    - name: "󰆴 Free disk space"
      run: |
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get clean
        df -h
    - name: "Checkout repository"
      uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17.0.9'
        distribution: 'graalvm-community'
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: "SonarCloud Scan"
      env:
        THRESHR_KEY: ${{ secrets.THRESHR_KEY }}
        THRESHR_CHANNEL: ${{ secrets.THRESHR_CHANNEL }}
        TEST_DATASOURCES_DEFAULT_URL: ${{ secrets.TEST_DATASOURCES_DEFAULT_URL }}
        GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B -V -Pcoverage -Dmaven.verify.skip=true test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        mvn -B -V verify -Dmaven.verify.skip=true org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      # on windows, add double quotes like below
      #.\mvnw -Pcoverage test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Graqr_Threshr
      #.\mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -D"sonar.projectKey=Graqr_Threshr"
